-- Documentation copy of engagement analytics schema v2.
-- The executable migration is SCHEMA_SQL in mrs_engagement_analytics.py.

-- Forward-only v2 migration (the executable applies each missing column
-- individually after inspecting PRAGMA table_info(post_pairs)):
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_id TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_plan_sha256 TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_pair_id TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_arm TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_member_position INTEGER;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_publication_order TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_experiment_sequence INTEGER;
--   ALTER TABLE post_pairs ADD COLUMN engagement_approved_question_sha256 TEXT;
--   ALTER TABLE post_pairs ADD COLUMN engagement_question_present INTEGER;
--   ALTER TABLE post_pairs ADD COLUMN engagement_public_text_sha256 TEXT;
-- Existing rows retain NULL for every experiment field. Existing post-pair
-- revisions and append-only metric snapshots are not rewritten.
-- Writable discovery and scheduled collection run this migration before using
-- the database. The read-only status command reports an existing v1 database as
-- migration-required rather than ready.

-- post_pairs: one auditable main quote/context relationship.
-- post_pair_revisions: append-only discovery revisions.
-- posts: main_quote and historical_context post identities.
-- snapshot_schedule: fixed 1h, 6h, 24h, 72h and 168h targets.
-- metric_snapshots: append-only successful or terminal observations.
-- metric_snapshot_revision_audit: reason and superseded row for corrected observations.
-- collection_attempts: append-only request/transport history.
-- account_or_capability_state: collector-only cooldown and capability state.
-- schema_migrations: applied local schema versions.

-- Inspect the authoritative live schema without writing:
--   sqlite3 'file:engagement_analytics.sqlite3?mode=ro' '.schema'
